blank_issues_enabled: false
contact_links:
  - name: SchoolConnect Community Discussions
    url: https://github.com/Yash-Singh1/schoolconnect-support-tracker/discussions
    about: Please ask and discuss questions, open ideas, etc. open here.
  - name: Security Vulnerability Reporting
    url: https://github.com/Yash-Singh1/schoolconnect-support-tracker/blob/main/README.md
    about: Please report security vulnerabilities here.
